### ISSUE TITLE
Unable to receive notifications

### ISSUE THREAD

**Issue by frncistic** [Clon1998/mobileraker_companion#25]
![Snipaste_2023-04-16_02-55-33](https://user-images.githubusercontent.com/44646627/232248395-0913adc4-88c0-4296-bbd7-02ae2e58b268.png)

**Comment by Clon1998** [comment]
Hey,
by looking at the images, I assume you are located in China?
It seems like the GFW is blocking the connection to my servers. I will look into options in order to resolve this issue for you, as I recently got another user reporting problems while trying to open the app itself (Which I assume is also caused by the GFW  as I am relying on Google's firebase for push notifications).

**Comment by frncistic** [comment]
yeah， so i  use  vpn    I try to change the network settings. Thank you

**Comment by frncistic** [comment]
![Snipaste_2023-04-18_14-12-50](https://user-images.githubusercontent.com/44646627/232687550-81a98fe0-24bd-4a0b-ad95-d19a7a0165b2.png)
![Snipaste_2023-04-18_14-13-14](https://user-images.githubusercontent.com/44646627/232687558-4ba955db-f1d7-4c7e-a5f7-0d05c11fbb0e.png)


It will still cause the same problem

**Comment by frncistic** [comment]
![Snipaste_2023-04-18_14-14-51](https://user-images.githubusercontent.com/44646627/232687836-5558ba94-1bfe-47b1-85cb-602055be3ad1.png)
