### ISSUE TITLE
Installing this will easily cause my host computer CPU to be overloaded, how to uninstall it?

### ISSUE THREAD

**Issue by zs96500** [Clon1998/mobileraker_companion#51]
Installing this will easily cause my host computer CPU to be overloaded, how to uninstall it?

**Comment by Clon1998** [comment]
You can try to switch to the `rewrite` branch since it seems to be a lot more stable and less CPU hungry by my testing.

However,
if you want to remove the companion you can either use [kiauh](https://github.com/Clon1998/mobileraker_companion#kiauh).

Or you use the `remove-mobileraker-companion.sh` script.
```bash
cd ~/mobileraker_companion
./scripts/remove-mobileraker-companion.sh
cd ~
rm -r ~/mobileraker_companion 
```
