### ISSUE TITLE
Phantom Messages of a excluded printer

### ISSUE THREAD

**Issue by dhnsilva** [Clon1998/mobileraker_companion#52]
I am receiving messages of an excluded printer. 
I had a cartesian printer called N955 and I trasform it on a Corexy. 
Renewed the Klipper and reinstalled all needs. 
Reinstalled the Mobileraker as a new name Q300. 

Now I am receiving a duplicate messages of mobileraker of a N955 and Q300 as the same printer.

I don't know where I can find this duplicate or old entry to erase! 
Can someone help me?

![IMG_25808942F622-1](https://github.com/Clon1998/mobileraker_companion/assets/16030426/2820ddfe-ece5-45b0-95ea-766af5716c7f)

**Comment by Clon1998** [comment]
Hey,
mobileraker stores information about the printer+push notification device, inside Moonraker's database.
There are some rare edge cases in which the deletion of a printer does not fully remove the printer from this database which can cause these ghost notifications.
In order to resolve that issue you will need to delete the database entry of mobileraker. Currently, this is not possible from within the app but will be included in a future release.

In order to manually delete the database entry, you will need to issue the following HTTP-DELETE: `DELETE http://<PRINTER-IP>/server/database/item?namespace=mobileraker&key=fcm`. You can do that either via console or any other HTTP client. 

For example, you can run the following code from within your brower's development console (Press F12 to open it), please make sure your current browser window is showing your printers web UI (e.g. Mainsail or FLuidd):

```js
fetch("http://<PRINTER-IP>/server/database/item?namespace=mobileraker&key=fcm", { method: "DELETE"} )
```

**Comment by dhnsilva** [comment]
Thank you!
Its Worked like a charm!
